version: "3"
services:
  backend:
    build: ./backend
    image: backend
    ports:
      - "8585:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FLASK_RUN_PORT: "5000"
      FLASK_HOST: "0.0.0.0"
  
  frontend:
    build: ./todo-list
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-list:/user/src/app
    depends_on:
      - backend
