version: "3"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    ports:
      - "8585:8585"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    command: flask run
  
  frontend:
    build:
      context: ./todo-list
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-list:/usr/src/app
    depends_on:
      - backend
    env_file:
      - ./todo-list/.env
    command: sh -c "npm install && npm start"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    volumes:
      - "./db/pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: