"""empty message

Revision ID: ad7c2ea0002a
Revises: 0bce3a5de9b6
Create Date: 2023-07-19 15:29:08.578114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7c2ea0002a'
down_revision = '0bce3a5de9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('isCompleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('isDisabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDisabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_disabled')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
